### ISSUE TITLE
sequelize와 webpack 에러

### ISSUE THREAD

**Issue by kyu9341** [boostcamp-2020/IssueTracker-35#5]
Github 로그인을 구현하기 전에 express 의 틀이 너무 안잡혀있는 것 같아서 issue 및 user 에 대한 sevice와 controller를 간단히 구현하고 시작하려 했습니다. 

먼저 `sequelize` 설정을 추가하고 웹팩으로 빌드를 하니 아래와 같은 오류가 발생합니다.

![sequelize_error](https://user-images.githubusercontent.com/49153756/97404729-e3c37580-1939-11eb-9b5a-d25e83acf84c.png)

- [https://github.com/sequelize/sequelize/issues/7509](https://github.com/sequelize/sequelize/issues/7509)

위의 링크를 참고하여 웹팩 설정에 `externals: ['pg', 'sqlite3', 'tedious', 'pg-hstore'],` 를 추가하니 빌드는 성공했지만 실행을 시킬 때 아래와 같이 빌드가 되며 오류가 발생했습니다.

![build_error](https://user-images.githubusercontent.com/49153756/97404758-ec1bb080-1939-11eb-9c97-bb50fb10cb69.png)

```
Error: Please install mysql2 pac
![build_error](https://user-images.githubusercontent.com/49153756/97404744-e6be6600-1939-11eb-9d00-5f7ad93fb5be.png)
kage manually
    at p._loadDialectModule (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1045265)
    at new p (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1156913)
    at new l (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1160919)
    at new A (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1316285)
    at Object.5386 (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1211)
    at __webpack_require__ (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1439628)
    at Object.54161 (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:993)
    at __webpack_require__ (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1439628)
    at Object.706 (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:911)
    at __webpack_require__ (/Users/kwon/Documents/doc_kwon/kwon/IssueTracker-35/server/dist/bundle.js:2:1439628)
```

위의 오류에 대해 찾아보니 `mysql2` 를 전역으로 설치해보라는 말이 있어서 해봤지만 계속 똑같은 오류가 발생합니다.

도움이 필요합니다!

**Comment by joh16** [comment]
webpack 사용 취소로 마무리지어야 해서 아쉽습니다 ㅠ

**Comment by kyu9341** [comment]
d
